---
  params:
    - "version"
    - "type"
  name: "jolokia/fish-pepper-java"
  buildVersion: 2
  jolokiaBaseUrl: "http://central.maven.org/maven2/org/jolokia/jolokia-jvm"
  jolokiaVersion: "1.3.1"
  maintainer: "roland@jolokia.org"
  config:
    version:
      openjdk-6:
        version: "1.6"
        java: "java:6b35"
        tags:
          - "6b35"
          - "6"
          - "openjdk-6"
        fullVersion: "OpenJDK 1.6.0_35 (6b35-1.13.7-1~deb7u1)"
      openjdk-7:
        version: "1.7"
        java: "java:7u79"
        tags:
          - "7u79"
          - "7"
          - "openjdk-7"
          - "latest"
        fullVersion: "OpenJDK 1.7.0_79 (7u79-2.5.5-1~deb8u)"
      openjdk-8:
        version: "1.8"
        java: "java:8u45"
        tags:
          - "8u45"
          - "8"
          - "openjdk-8"
        fullVersion: "OpenJDK 1.8.0_45 (1.8.0_45-internal-b14)"
    type:
      jre:
      jdk:
